name: rgr
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.6

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  dotenv: ^4.2.0
  path: ^1.9.0
  postgres: ^3.5.9

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
